name: river-dl2
channels:
    - pytorch
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - git
    - pytorch
    - torchvision
    - torchaudio
    - pip
    - jupyterlab
    - matplotlib
    - pandas
    - python==3.9
    - pyarrow
    - scikit-learn
    - snakemake=5.3.0
    - xarray
    - zarr
    - tqdm
    - dask
    - tensorflow # or tensorflow-gpu
